### PR TITLE
Quality 137/improve serialization deserialization

### LINKED ISSUE #137: Improve binary read/write for code readability
There's a good opportunity to make the code more readable when it comes to serialization/deserialization of many classes (like grids, file source/sinks, coords, etc).  

currently, the code looks like this:
```Rbt::WriteWithThrow(ostr, (const char*)&m_NX, sizeof(m_NX));```

improvements:
1. we should replace this `(const char*)` casting with a `reinterpret_cast`
2. encapsulate all this within a templated function
3. explicitly set the flags for ostream right after instantiation to automatically raise an exception in case an operation fails(`ostr.exceptions(...)`)

### PR DESCRIPTION
**Pull request by ggutierrez-sunbright**
Added:
* auxiliary functions for binary read and write
* auxiliary function to check for class name during deserialization
* test to verify the new `.as` files generated are identical to the original ones (for retro-compatibility)
* some additional code quality improvements

closes #137

### CODE REVIEW

File: src/lib/RbtBaseFileSink.cxx [hunk 1]
```diff
@@ -101,8 +97,11 @@ void RbtBaseFileSink::ReplaceLine(const RbtString& fileRec, RbtUInt nRec) {
 void RbtBaseFileSink::Open(RbtBool bAppend) {
     std::_Ios_Openmode openMode = ios_base::out;
     if (bAppend) openMode = openMode | ios_base::app;
-    m_fileOut.open(m_strFileName.c_str(), openMode);
-    if (!m_fileOut) throw RbtFileWriteError(_WHERE_, "Error opening " + m_strFileName);
+    try {
+        m_fileOut.open(m_strFileName.c_str(), openMode);
```
Comment (ggutierrez-sunbright) [inline src/lib/RbtBaseFileSink.cxx:101]:
```suggestion
        m_fileOut.open(m_strFileName, openMode);
```
